services:
  postgres:
    image: postgres:15-alpine
    container_name: tasf-b2b-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tasf_b2b}
      POSTGRES_USER: ${POSTGRES_USER:-tasf}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tasf123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tasf-network

  redis:
    image: redis:7-alpine
    container_name: tasf-b2b-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - tasf-network

  mongo:
    image: mongo:7
    container_name: tasf-b2b-mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-tasf_b2b}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tasf-network

  backend:
    build:
      context: ./modules/backend
      dockerfile: Dockerfile
    container_name: tasf-b2b-backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    volumes:
      - ./modules/backend/src/test/resources/datos:/app/src/test/resources/datos
    environment:
      PLANNER_DATASETS_DEMO_AEROPUERTOS: ${PLANNER_DATASETS_DEMO_AEROPUERTOS:-/app/src/test/resources/datos/estudiantes.txt}
      PLANNER_DATASETS_DEMO_VUELOS: ${PLANNER_DATASETS_DEMO_VUELOS:-/app/src/test/resources/datos/planes_vuelo.txt}
      PLANNER_DATASETS_DEMO_ENVIOS_DIR: ${PLANNER_DATASETS_DEMO_ENVIOS_DIR:-/app/src/test/resources/datos/envios_preliminar_test}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-tasf_b2b}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-tasf}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-tasf123}
    depends_on:
      - postgres
      - redis
      - mongo
    networks:
      - tasf-network

  frontend:
    build:
      context: ./modules/frontend
      dockerfile: Dockerfile
    container_name: tasf-b2b-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - tasf-network

networks:
  tasf-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: