spring.application.name=TasfB2B-DHGS

# Servidor
server.port=8080

# Rutas de datos de entrada
app.data.path=./data
app.data.aeropuertos=./data/estudiantes.txt
app.data.vuelos=./data/planes_vuelo.txt

# Parámetros del algoritmo DHGS
app.dhgs.duracion-epoca-horas=4
app.dhgs.tamano-poblacion=25
app.dhgs.limite-tiempo-segundos=300

# Logging
logging.level.com.TasfB2B.DHGS=DEBUG
