spring.application.name=TasfB2B-DHGS

# Servidor
server.port=8080

# Configuracion base del planificador
planner.defaults.epoch-hours=4
planner.defaults.population-size=6
planner.defaults.time-limit-seconds=2

# Datasets de trabajo para desarrollo local
planner.datasets.demo.aeropuertos=src/test/resources/datos/estudiantes.txt
planner.datasets.demo.vuelos=src/test/resources/datos/planes_vuelo.txt
planner.datasets.demo.envios-dir=src/test/resources/datos/envios_preliminar_test

planner.datasets.real.aeropuertos=src/test/resources/datos/estudiantes_real.txt
planner.datasets.real.vuelos=src/test/resources/datos/planes_vuelo_real.txt
planner.datasets.real.envios-dir=src/test/resources/datos/envios_preliminar

# Logging
logging.level.com.tasfb2b.dhgs=DEBUG
logging.level.com.tasfb2b.backend=DEBUG
